# permissions for end users to view jenkinspipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkinspipeline-viewer-role
rules:
- apiGroups:
  - opswagon.xbc.io
  resources:
  - jenkinspipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opswagon.xbc.io
  resources:
  - jenkinspipelines/status
  verbs:
  - get
