# permissions for end users to view jenkinsplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkinsplugin-viewer-role
rules:
- apiGroups:
  - opswagon.xbc.io
  resources:
  - jenkinsplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opswagon.xbc.io
  resources:
  - jenkinsplugins/status
  verbs:
  - get
